#!/usr/bin/env python3

from cloversim.task import WORLD_PATH, task_pkg
import sys
import rospy
import subprocess

myargv = rospy.myargv(argv=sys.argv)

def generate_world():
  subprocess.run(["rosrun", task_pkg, "generate_world.py"])
  return WORLD_PATH

cmd = myargv[1]

if cmd == "generate_world":
  print("World generated, path:", generate_world())
