name: Build

on: 
  push:
  pull_request:
  release:
    types: [created]

jobs:
  base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl

      - uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install dependencies
        run: |
          sudo apt install -y musl-tools

      - name: Build
        run: |
          ./build_release.sh
          
      - name: Copy cloversim to root and create zip
        run: |
          cp ./target/x86_64-unknown-linux-musl/release/cloversim ./cloversim
          mkdir workspaces containers
          zip -r cloversim.zip virgl tasks sim cloversim workspaces containers
      
      - name: Upload artifact
        uses: actions/upload-artifact@v2.2.0
        with:
          name: cloversim
          path: |
            virgl
            tasks
            sim
            cloversim
    
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        if: ${{ github.event_name == 'release' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }} 
          asset_path: ./cloversim.zip
          asset_name: cloversim.zip
          asset_content_type: application/zip
  
