name: Build

on: 
  push:
  pull_request:
  release:
    types: [created, edited, released]

jobs:
  base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.5'

      - name: Build
        working-directory: src
        run: |
          go build -o ../clover_sim
          
      - name: Upload
        uses: actions/upload-artifact@v2.2.0
        with:
          name: clover_sim
          path: |
            virgl
            clover_sim
  