name: Build

on: 
  push:
  pull_request:
  release:
    types: [created]

jobs:
  base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
          
      - name: Copy cloversim to root and create zip
        run: |
          cp ./target/release/cloversim ./cloversim
          zip -r cloversim.zip virgl tasks sim cloversim
      
      - name: Upload artifact
        uses: actions/upload-artifact@v2.2.0
        with:
          name: cloversim
          path: |
            virgl
            tasks
            sim
            cloversim
    
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        if: ${{ github.event_name == 'release' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }} 
          asset_path: ./build/cloversim.zip
          asset_name: cloversim.zip
          asset_content_type: application/zip
  
